apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: tanzusp
  claimRef:
    name: jenkins-pv-claim
    namespace: jenkins
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  storageClassName: tanzusp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
