apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-claim
  namespace: jenkins
spec:
  storageClassName: tanzusp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi