apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: spring
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuZGF0YW1hcmtldC5sb2NhbDo5NDQzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlVHRnpjekV5TXpRaCIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuMTUgKGxpbnV4KSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
