kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv  
  namespace: postgres
  labels:
    app: postgres
spec:
  storageClassName: tanzusp
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
