apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  namespace: postgres
  labels:
    app: postgres # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      
  selector:
    app: postgres
